#!/usr/bin/env bash
# End-to-end local validation for parent_query_id linkage.
#
# Drives pg_stat_ch through the OTel/Arrow export path (the production
# pathway) with debug_arrow_dump_dir set so each Arrow IPC batch is
# written to a host-mounted directory.  We then parse the IPC files with
# pyarrow (via uv) and assert that:
#
#   1. Top-level queries report parent_query_id = 0.
#   2. Nested SPI queries report parent_query_id = outer's query_id.
#   3. Log events captured by emit_log_hook while a nested SPI query is
#      on the stack carry query_id of the running (inner) statement and
#      parent_query_id of the outer caller (catches CaptureLogEvent's
#      off-by-one).  We use RAISE WARNING for this rather than a caught
#      ERROR: emit_log_hook does not fire from errfinish for ERROR-level
#      events (errfinish PG_RE_THROWs before EmitErrorReport runs;
#      emit_log_hook only fires later from PostgresMain's top-level
#      catch, after all frames have been popped — or never, for errors
#      caught inside a plpgsql EXCEPTION block).  WARNING goes through
#      EmitErrorReport directly so the frame stack is intact when our
#      hook runs.
#
# Why not the native ClickHouse path?  clickhouse-cpp's LZ4-compressed
# block format currently triggers a checksum-mismatch on ClickHouse 26.1
# server (separate, pre-existing bug).  The OTel/Arrow path uses ZSTD via
# Arrow IPC and is unaffected; it also mirrors what we ship in prod.
#
# Requirements: docker compose, uv (`brew install uv` / `pip install uv`).
# First-time `up` builds the postgres image (~10-15 min cold; cached afterwards).

set -euo pipefail

COMPOSE_FILE="docker/quickstart/docker-compose.otel.yml"
DUMP_DIR="docker/quickstart/arrow-dump"
PASSED=0
FAILED=0

if ! command -v uv >/dev/null 2>&1; then
  echo "error: uv not found in PATH.  Install with 'brew install uv' or 'pip install uv'." >&2
  exit 1
fi

pg_exec() {
  docker compose -f "$COMPOSE_FILE" exec -T postgres \
    psql -U postgres -d postgres -v ON_ERROR_STOP=1 "$@"
}

ensure_stack_up() {
  if ! docker compose -f "$COMPOSE_FILE" ps --status running 2>/dev/null | grep -q postgres; then
    echo "OTel/Arrow quickstart stack not running.  Bringing it up..."
    # Reuse the image built by ./scripts/quickstart.sh up
    if ! docker image inspect quickstart-postgres:latest >/dev/null 2>&1; then
      echo "  Building image first (one-time, ~10-15 min cold)..."
      docker compose -f docker/quickstart/docker-compose.yml build postgres
    fi
    docker compose -f "$COMPOSE_FILE" up -d --wait
  fi
}

expect() {
  local name="$1" expected="$2" actual="$3" comparator="${4:-=}"
  local ok=0
  case "$comparator" in
    '=')  [[ "$actual" == "$expected" ]] && ok=1 ;;
    '>=') [[ "$actual" -ge "$expected" ]] && ok=1 ;;
  esac
  if [[ "$ok" -eq 1 ]]; then
    printf '  \033[32mPASS\033[0m  %s\n' "$name"
    PASSED=$((PASSED + 1))
  else
    printf '  \033[31mFAIL\033[0m  %s (expected %s %s, got %s)\n' \
      "$name" "$comparator" "$expected" "$actual"
    FAILED=$((FAILED + 1))
  fi
}

ensure_stack_up

echo "Resetting state and setting up fixtures..."
rm -f "$DUMP_DIR"/*.ipc 2>/dev/null || true

pg_exec <<'SQL' >/dev/null
CREATE EXTENSION IF NOT EXISTS pg_stat_ch;
SELECT pg_stat_ch_reset();

DROP TABLE IF EXISTS pqid_top_marker CASCADE;
DROP TABLE IF EXISTS pqid_inner_marker CASCADE;
DROP TABLE IF EXISTS pqid_warn_tbl CASCADE;
DROP FUNCTION IF EXISTS pqid_outer_caller();
DROP FUNCTION IF EXISTS pqid_warn_outer();
DROP FUNCTION IF EXISTS pqid_emit_warn(int);

CREATE TABLE pqid_top_marker(x int);
CREATE TABLE pqid_inner_marker(x int);
INSERT INTO pqid_inner_marker VALUES (1);
CREATE TABLE pqid_warn_tbl(x int);
INSERT INTO pqid_warn_tbl VALUES (1);

CREATE FUNCTION pqid_outer_caller() RETURNS int
LANGUAGE plpgsql AS $$
DECLARE v int;
BEGIN
  SELECT x INTO v FROM pqid_inner_marker;
  RETURN v;
END$$;

CREATE FUNCTION pqid_emit_warn(x int) RETURNS int
LANGUAGE plpgsql AS $$
BEGIN
  RAISE WARNING 'pqid_warn_marker' USING ERRCODE = '01001';
  RETURN x;
END$$;

CREATE FUNCTION pqid_warn_outer() RETURNS int
LANGUAGE plpgsql AS $$
DECLARE v int;
BEGIN
  SELECT pqid_emit_warn(x) INTO v FROM pqid_warn_tbl;
  RETURN v;
END$$;
SQL

# Clear dumps generated by setup, then drive the test queries.
rm -f "$DUMP_DIR"/*.ipc 2>/dev/null || true
pg_exec -c "SELECT pg_stat_ch_reset();" >/dev/null

echo "Driving test queries..."
pg_exec <<'SQL' >/dev/null
SELECT * FROM pqid_top_marker;
SELECT count(*) FROM pqid_top_marker;
SELECT pqid_outer_caller();
SELECT pqid_warn_outer();
SELECT pg_stat_ch_flush();
SQL

# Wait for IPC files to land.
echo "Waiting for Arrow IPC dumps..."
for _ in $(seq 1 30); do
  if compgen -G "$DUMP_DIR"/*.ipc >/dev/null; then break; fi
  sleep 1
done

# Parse the dumped Arrow IPC batches and run assertions.  We emit one
# `KEY=VALUE` line per assertion result from the inline pyarrow script so
# the shell can pick them up without re-implementing Arrow parsing.
results=$(uv run --quiet --with pyarrow --python 3.12 - "$DUMP_DIR" <<'PY'
import glob, os, sys
import pyarrow as pa
import pyarrow.ipc as ipc

dump_dir = sys.argv[1]
rows = []
for path in sorted(glob.glob(os.path.join(dump_dir, "*.ipc"))):
    with open(path, "rb") as f:
        reader = ipc.open_stream(f)
        table = reader.read_all()
    for batch_dict in table.to_pylist():
        rows.append(batch_dict)

def has(text, predicate=None):
    out = []
    for r in rows:
        q = r.get("query_text") or ""
        if text in q and (predicate is None or predicate(r)):
            out.append(r)
    return out

def by_query_id(qid):
    return [r for r in rows if r.get("query_id") == qid]

# Arrow dict-encodes query_id and parent_query_id as decimal *strings*; "0"
# means top-level / no parent.  Compare against strings, not ints.
def is_zero(v):
    return v is None or v == "" or v == "0"

# Test 1: top-level marker queries report parent_query_id == 0
top_rows = has("pqid_top_marker")
top_with_nonzero_parent = [r for r in top_rows if not is_zero(r.get("parent_query_id"))]
print(f"top_rows={len(top_rows)}")
print(f"top_nonzero_parent={len(top_with_nonzero_parent)}")

# Test 2: nested SPI inner.parent_query_id matches outer.query_id.  Filter
# to SELECT so the setup CREATE TABLE / INSERT / DROP utility statements
# (which mention the table) don't pollute the "no orphans" check.
outer_rows = [r for r in has("pqid_outer_caller") if r.get("db_operation") == "SELECT"]
inner_rows = [r for r in has("pqid_inner_marker") if r.get("db_operation") == "SELECT"]
linked = 0
for inner in inner_rows:
    p = inner.get("parent_query_id")
    if not is_zero(p) and any(o.get("query_id") == p for o in outer_rows):
        linked += 1
inner_orphans = [r for r in inner_rows if is_zero(r.get("parent_query_id"))]
outer_self_parent = [r for r in outer_rows if not is_zero(r.get("parent_query_id"))]
print(f"outer_rows={len(outer_rows)}")
print(f"inner_rows={len(inner_rows)}")
print(f"inner_linked_to_outer={linked}")
print(f"inner_with_zero_parent={len(inner_orphans)}")
print(f"outer_with_nonzero_parent={len(outer_self_parent)}")

# Test 3: log event captured inside nested SPI (via RAISE WARNING).
# The event has no query_text (CaptureLogEvent leaves it empty), so we
# identify it by err_sqlstate '01001' (our RAISE WARNING's custom code).
warn_outer = [r for r in has("pqid_warn_outer") if r.get("db_operation") == "SELECT"]
warn_inner = [r for r in has("pqid_emit_warn") if r.get("db_operation") == "SELECT"]
warn_outer_qids = {r.get("query_id") for r in warn_outer if not is_zero(r.get("query_id"))}
warn_inner_qids = {r.get("query_id") for r in warn_inner if not is_zero(r.get("query_id"))}
warn_rows = [r for r in rows if r.get("err_sqlstate") == "01001"]
warn_linked_to_outer = sum(1 for r in warn_rows
                           if r.get("parent_query_id") in warn_outer_qids)
warn_qid_is_inner = sum(1 for r in warn_rows if r.get("query_id") in warn_inner_qids)
warn_qid_is_outer = sum(1 for r in warn_rows if r.get("query_id") in warn_outer_qids)
warn_self_parent = sum(1 for r in warn_rows
                       if not is_zero(r.get("query_id"))
                       and r.get("query_id") == r.get("parent_query_id"))
print(f"warn_rows={len(warn_rows)}")
print(f"warn_linked_to_outer={warn_linked_to_outer}")
print(f"warn_qid_is_inner={warn_qid_is_inner}")
print(f"warn_qid_is_outer={warn_qid_is_outer}")
print(f"warn_self_parent={warn_self_parent}")
PY
)

echo "$results"
echo

# Pull individual values out.
get() { echo "$results" | awk -F= -v k="$1" '$1==k {print $2}'; }

echo "Test 1: top-level queries report parent_query_id = 0"
expect "top-level rows landed"        1 "$(get top_rows)"                  '>='
expect "top-level parent_query_id = 0" 0 "$(get top_nonzero_parent)"

echo
echo "Test 2: nested SPI parent_query_id links to outer query_id"
expect "outer rows landed"             1 "$(get outer_rows)"               '>='
expect "inner rows landed"             1 "$(get inner_rows)"               '>='
expect "inner row joins outer via parent_query_id" 1 "$(get inner_linked_to_outer)" '>='
expect "nested SPI is not reported as top-level"    0 "$(get inner_with_zero_parent)"
expect "outer call still reports parent_query_id = 0" 0 "$(get outer_with_nonzero_parent)"

echo
echo "Test 3: log event inside nested SPI"
expect "RAISE WARNING log event landed"                 1 "$(get warn_rows)"           '>='
expect "log event parent_query_id = outer's query_id"   1 "$(get warn_linked_to_outer)" '>='
expect "log event query_id = inner SPI (the running)"   1 "$(get warn_qid_is_inner)"   '>='
expect "log event query_id is NOT outer (no off-by-one)" 0 "$(get warn_qid_is_outer)"
expect "log event query_id != parent_query_id"          0 "$(get warn_self_parent)"

echo
echo "Cleaning up fixtures..."
pg_exec <<'SQL' >/dev/null
DROP FUNCTION IF EXISTS pqid_outer_caller();
DROP FUNCTION IF EXISTS pqid_warn_outer();
DROP FUNCTION IF EXISTS pqid_emit_warn(int);
DROP TABLE IF EXISTS pqid_top_marker;
DROP TABLE IF EXISTS pqid_inner_marker;
DROP TABLE IF EXISTS pqid_warn_tbl;
SQL

echo
echo "==================================================="
printf "Result: \033[32m%d passed\033[0m, \033[31m%d failed\033[0m\n" "$PASSED" "$FAILED"
echo "==================================================="
[[ "$FAILED" -eq 0 ]]
