name: 🚀 Bundle & Release on PGXN
on:
  push:
jobs:
  release:
    name: Release on PGXN
    runs-on: depot-ubuntu-24.04-16
    container: pgxn/pgxn-tools
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with: { submodules: recursive, fetch-depth: 0 }
      - name: Bundle the Release
        env: { GIT_ARCHIVE_CMD: archive-all }
        id: bundle
        run: pgxn-bundle
      - name: Release on PGXN
        if: startsWith( github.ref, 'refs/tags/v' )
        env:
          PGXN_USERNAME: ${{ secrets.PGXN_USERNAME }}
          PGXN_PASSWORD: ${{ secrets.PGXN_PASSWORD }}
        run: pgxn-release
